image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      mysql < blog-api/src/main/resources/sql/blog-schema.sql
      mysql < blog-api/src/main/resources/sql/blog-data.sql
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';"
  - init: |
      cd blog-api
      mvn install -DskipTests=true
    command: java -jar target/blog-api-0.0.1-SNAPSHOT.jar
  - init: |
      cd blog-app
      npm install
      npm run build
    command: npm run dev

ports:
- port: 8888
  onOpen: open-preview
  visibility: public
- port: 8080
  onOpen: open-preview
  visibility: public
- port: 3306
  onOpen: ignore
  visibility: public
- port: 6379
  onOpen: ignore
  visibility: public

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true